### ISSUE TITLE
Hello, do you have the corresponding simulation files.

### ISSUE THREAD

**Issue by wtuo1046** [IhabMohamed/ANN-MPC#1]
Hello, do you have the corresponding simulation files.

**Comment by IhabMohamed** [comment]
Hi @wtuo1046,

Are you still interested in having the Simulink files? If so, simply, you should replace the **MPC block** in [MPC_3Phase_Inverter.slx](https://github.com/IhabMohamed/MPC-3-Phase-Inverters/blob/master/MPC_3Phase_Inverter.slx) with the `trained ANN`. 

Regards,
Ihab

**Comment by wtuo1046** [comment]
Thank you for your reply, I have a clear understanding of the system, your work has given me great inspiration, and now I am doing other further attempts.

Regards,
Wtuo

发送自 Windows 10 版邮件应用

发件人: Ihab S. Mohamed
发送时间: 2019年9月9日 14:26
收件人: IhabMohamed/ANN-MPC
抄送: wtuo1046; Mention
主题: Re: [IhabMohamed/ANN-MPC] Hello, do you have the correspondingsimulation files. (#1)

Hi @wtuo1046,
Are you still interested in having the Simulink files? If so, simply, you should replace the MPC block in MPC_3Phase_Inverter.slx with the trained ANN.
Regards,
Ihab

**Comment by IhabMohamed** [comment]
@wtuo1046 , that's great, thanks ;-)

Let me know if you need any help and I am willing for any research collaboration as well.
